codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # basic
        # target: 14%
        threshold: 14%
        # base: auto 
        flags: 
          - unittests
        # paths: 
        #   - "src"
       # advanced
        branches: 
          - master
        if_not_found: failue
        if_ci_failed: error
        informational: false
        only_pulls: false
  # precision: 2
  # round: down
  # range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no