codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 1
        base: auto 
        flags: 
          - unittests
        paths: 
          - "/"
       # advanced
        branches: 
          - master
        if_not_found: failure
        if_ci_failed: error
        informational: false
        only_pulls: false
  precision: 2
  round: down
  range: "30...90"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "test_*.rb"       # wildcards accepted
  - "**/*.py"         # glob accepted
  - "**/*.md"
  - "**/*.mod"
  - "**/*.sum"
  - "**/*.yml"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no